### ISSUE TITLE
Azure: SSG in paused state

### ISSUE THREAD

**Issue by net47** [f5devcentral/f5-big-iq-trial#8]
Dear team, 
I have deployed the "existing VNET/no demo app" ARM template, but unfortunately the SSG isn't coming up. I see the following error in /var/log/restjavad.0.log

```[INFO][04 Feb 2019 13:14:38 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] Starting initial build out of ssg: azure-ssg
[INFO][04 Feb 2019 13:14:38 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] Polling: /mgmt/cm/cloud/orchestrator/azure/tasks/deploy-auto-scale/9d4867e8-2b99-4df5-8443-5b0c2fdd5a4f
[INFO][04 Feb 2019 13:14:38 PST][/cm/cloud/azure/images-info ImagesInfoWorker] Completed the retrieval of images list.
[WARN][04 Feb 2019 13:14:48 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] java.lang.Exception: Failed to trigger the flask task: java.lang.IllegalStateException: Deploying ARM template failed: Deployment failed for azure-ssg. Reason: Deployment failed with status code: 400 and message: The template deployment 'azure-ssg' is not valid according to the validation procedure. The tracking id is '4fe73c7a-6dc9-4d60-9320-3dd7bb50c0f9'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:144)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:119)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.ApacheAsyncRequestSender.lambda$completeRequestOnNonBlockingPool$5(ApacheAsyncRequestSender.java:374)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at com.f5.rest.workers.cloud.task.azure.step.CreateVMTask$1.failed(CreateVMTask.java:69)
	at com.f5.rest.workers.cloud.task.azure.step.CreateVMTask$1.failed(CreateVMTask.java:60)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:144)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:119)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.ApacheAsyncRequestSender.lambda$completeRequestOnNonBlockingPool$5(ApacheAsyncRequestSender.java:374)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR][04 Feb 2019 13:14:48 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] java.lang.Exception: Failed to trigger the flask task: java.lang.IllegalStateException: Deploying ARM template failed: Deployment failed for azure-ssg. Reason: Deployment failed with status code: 400 and message: The template deployment 'azure-ssg' is not valid according to the validation procedure. The tracking id is '4fe73c7a-6dc9-4d60-9320-3dd7bb50c0f9'. See inner errors for details. Please see https://aka.ms/arm-deploy for usage details.
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:144)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:119)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.ApacheAsyncRequestSender.lambda$completeRequestOnNonBlockingPool$5(ApacheAsyncRequestSender.java:374)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

	at com.f5.rest.workers.cloud.task.azure.step.CreateVMTask$1.failed(CreateVMTask.java:69)
	at com.f5.rest.workers.cloud.task.azure.step.CreateVMTask$1.failed(CreateVMTask.java:60)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:144)
	at com.f5.rest.workers.cloud.task.FlaskUtils$2.completed(FlaskUtils.java:119)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.ApacheAsyncRequestSender.lambda$completeRequestOnNonBlockingPool$5(ApacheAsyncRequestSender.java:374)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR][04 Feb 2019 13:14:48 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] Reject reentrant transition to status FAILED - java.lang.IllegalStateException
	at com.f5.rest.workers.configmgmtbase.task.BaseTaskWorker.endsReentrance(BaseTaskWorker.java:1136)
	at com.f5.rest.workers.configmgmtbase.task.BaseTaskWorker.allowedUpdate(BaseTaskWorker.java:1081)
	at com.f5.rest.workers.configmgmtbase.task.BaseTaskWorker.updateTaskStatus(BaseTaskWorker.java:981)
	at com.f5.rest.workers.configmgmtbase.task.BaseTaskWorker.updateStatus(BaseTaskWorker.java:921)
	at com.f5.rest.workers.configmgmtbase.task.BaseTaskWorker.updateStatus(BaseTaskWorker.java:943)
	at com.f5.rest.workers.cloud.task.azure.buildout.InitialBuildOutTaskWorker.updateStep(InitialBuildOutTaskWorker.java:236)
	at com.f5.rest.workers.cloud.task.azure.buildout.InitialBuildOutTaskWorker.access$200(InitialBuildOutTaskWorker.java:43)
	at com.f5.rest.workers.cloud.task.azure.buildout.InitialBuildOutTaskWorker$7.completed(InitialBuildOutTaskWorker.java:342)
	at com.f5.rest.workers.cloud.task.azure.buildout.InitialBuildOutTaskWorker$7.completed(InitialBuildOutTaskWorker.java:339)
	at com.f5.rest.workers.cloud.task.azure.BaseAzureTaskWorker$7.completed(BaseAzureTaskWorker.java:370)
	at com.f5.rest.workers.cloud.task.azure.BaseAzureTaskWorker$7.completed(BaseAzureTaskWorker.java:367)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.RestWorker$3.completed(RestWorker.java:685)
	at com.f5.rest.common.RestWorker$3.completed(RestWorker.java:678)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.common.RestCollectionWorker$18.completed(RestCollectionWorker.java:1879)
	at com.f5.rest.common.RestCollectionWorker$18.completed(RestCollectionWorker.java:1875)
	at com.f5.rest.common.RestWorker.indexCreateOrReplaceItem(RestWorker.java:1821)
	at com.f5.rest.common.RestCollectionWorker.handlePatchEvent(RestCollectionWorker.java:1875)
	at com.f5.rest.common.RestCollectionWorker.access$1300(RestCollectionWorker.java:59)
	at com.f5.rest.common.RestCollectionWorker$16.completed(RestCollectionWorker.java:1811)
	at com.f5.rest.common.RestCollectionWorker$16.completed(RestCollectionWorker.java:1805)
	at com.f5.rest.common.RestOperation.complete(RestOperation.java:2711)
	at com.f5.rest.workers.storage.StorageWorker$9.completed(StorageWorker.java:890)
	at com.f5.rest.workers.storage.StorageWorker$9.completed(StorageWorker.java:885)
	at com.f5.rest.workers.storage.TransactionRunnable$TxRunCompletion.run(TransactionRunnable.java:644)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[WARN][04 Feb 2019 13:14:48 PST][/cm/cloud/tasks/azure/initial-buildout/18f897df-44e2-4a5a-b9b1-ef34a832a4fc/worker InitialBuildOutTaskWorker] Reentrant update, dropping update to status FAILED
```

Thanks & br
Daniel

**Comment by rjouhann** [comment]
Hello Daniel,

Looking at the error message `"The template deployment 'azure-ssg' is not valid according to the validation procedure"`, could you share a screenshot of your SSG properties under **_Applications Tab > ENVIRONEMENTS > Service Scaling Groups > azure-ssg_**?

Could you check under **_Applications Tab > ENVIRONEMENTS > Cloud Providers_** and make sure the Connection Test is successful?

Thanks & Regards,
Roman

**Comment by net47** [comment]
Hi Roman,

sure, here are some screenshots:

![bildschirmfoto 2019-02-05 um 04 50 35](https://user-images.githubusercontent.com/12584109/52252297-f1350280-2901-11e9-84cc-b329e8135d05.png)

![bildschirmfoto 2019-02-05 um 04 51 23](https://user-images.githubusercontent.com/12584109/52252306-fb570100-2901-11e9-8f2e-d2fbc54202f5.png)

![bildschirmfoto 2019-02-05 um 04 52 06](https://user-images.githubusercontent.com/12584109/52252310-06119600-2902-11e9-936c-f89a5413bcaf.png)

regards
Daniel

**Comment by rjouhann** [comment]
Could you share entire logs /var/log/restjavad.0.log* and /var/log/orchestrator.log* in a zip file?
If you go under **_Devices > LICENSE MANAGEMENT > Licenses_**, do you see the BIG-IP being licensed?
Could you also check the logs in the Azure console?
Thanks!

**Comment by net47** [comment]
Sure:
[logs.zip](https://github.com/f5devcentral/f5-big-ip-cloud-edition-trial-quick-start/files/2830720/logs.zip)

License:
![bildschirmfoto 2019-02-05 um 05 22 12](https://user-images.githubusercontent.com/12584109/52253122-57238900-2906-11e9-922f-fb0d40eec6f9.png)

What exact logs do you need from Azure?

**Comment by rjouhann** [comment]
Thanks for the logs. I am looking into it.

Could you confirm you have "Enable programmatic deployment" for the _**F5 BIG-IP VE – ALL (BYOL, 1 Boot Location)**_ and setting up your Service Principal Account for the Service Scaling Group as described in the step 3.?

Could you click on the Failed Deployment in Azure Portal, click on the Activity Log and navigate to the failed step. Click on the JSON view and look at the "status" field. The inner exception will have the reason for the failure.

You run up against a resource limit (number of CPUs on the subscription).

There would be two ways to solve the issue: request an increase to the subscription account or delete other instances in the account that use CPUS.

You may also try to reactivate the SSG in case it would be an intermittent failure caused by an error in ARM deployment in Azure.

**Comment by net47** [comment]
'programmatic deployment' is enabled on all images. 

It's pretty strange because I'm using an plain 'outlook.com' Azure account which has a paid subscription and nothing running beside the Azure F5 template. I'm now increasing my limits/quotas, maybe this fixes our issue, and keep you updated.
